### ISSUE TITLE
What version of vdhcoapp for Video DownloadHelper 7.3.6

### ISSUE THREAD

**Issue by BlackMage2** [mi-g/vdhcoapp#123]
What version of vdhcoapp is valid for DownloadHelper 7.3.6? i have version 10.4.1(.0) of the CoApp[from VdhCoAppSetup-1.2.4.exe] installed and doesn´t know what version is valid for these. The VdhCoApp is not recognized anyway.

Is there a list of assignments somewhere?

**Comment by BlackMage2** [comment]
in registry is saved that:
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\DownloadHelper\net.downloadhelper.coapp]
"InstallFolder"="C:\\Program Files\\net.downloadhelper.coapp"
"Version"="1.2.4"

**Comment by BlackMage2** [comment]
and in the settings of the addon in firefox is always "Verifying Companion App…" written.

**Comment by BlackMage2** [comment]
the companion app is running, but it is not recognized

**Comment by mi-g** [comment]
The backward compatibility of the coapp has always been maintained since the move to WebExtensions with VDH 6.0.0 and vdhcoapp 1.0.0. This means the best version of the coapp for VDH 7.x is always the latest one, currently it's 1.6.3.
You should ask your question to the VDH support forum https://groups.google.com/g/video-downloadhelper-q-and-a . Start with making a search first. If you post, please make sure you mention the browser you are using as this could be the issue here.

**Comment by BlackMage2** [comment]
ehm, the forum is closed. no one can post in the google groups forum
