### ISSUE TITLE
Keeping showing "Verifying Companion App..." on Linux

### ISSUE THREAD

**Issue by kuanyui** [mi-g/vdhcoapp#39]
First, thanks for developing this awesome Firefox plugin.

I encounter a phenomenon similar to #4 , after cloning, building & installing (without root privilege) vdhcoapp, restarting Firefox, and Video DownloadHelper hangs at `Verifying Companion App...` like this:
![screenshot_20181004_215501](https://user-images.githubusercontent.com/1370070/46479178-182edb00-c821-11e8-9bf9-d54545d83dd9.png)
I checked the executable path & permission in `~/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json`, but it seems no problem...?
![screenshot_20181004_220232](https://user-images.githubusercontent.com/1370070/46479230-3399e600-c821-11e8-8ea9-3e5677918c47.png)

I cannot see any error message or logs about it. What can I do to find out where the problem is? Thanks.

**Comment by mi-g** [comment]
The companion app on the github repository is the one we compile and distribute, so i am reasonably confident that the overall system is working.
You may want to recheck all possible manifest locations so that you don't have left a corrupted manifest somewhere, try on Chrome as you may have a more explicit error/warning message in the browser console, ...

**Comment by kuanyui** [comment]
I just tested on Chrome & Chromium:
1. They also hanged at `Verifying Companion App...`, but after clicking `Recheck` times, it said `
```
Companion App not installed
Checking companion app returned: Native host has exited.
```
![screenshot_20181005_094351](https://user-images.githubusercontent.com/1370070/46511822-7a202c80-c883-11e8-9bd3-99136d91a3d2.png)
![screenshot_20181005_094540](https://user-images.githubusercontent.com/1370070/46511823-7a202c80-c883-11e8-8641-154ead46b912.png)
2. Console of the browsers shows nothing.
3. `~/.config/google-chrome/NativeMessagingHosts` looks like this:
![screenshot_20181005_095045](https://user-images.githubusercontent.com/1370070/46512003-54475780-c884-11e8-9071-a1d7261201db.png)

>You may want to recheck all possible manifest locations so that you don't have left a corrupted manifest somewhere
 BTW, what is the expected output after executing `net.downloadhelper.coapp-linux-64` ? I run it without ARGV, it hangs without any output. (Surely I can see `VdhCoApp: VdhCoApp is ready to be used` if with `install` argument)

**Comment by mi-g** [comment]
The problem has not been reported for 2 years. Closing the issue.

**Comment by ctrlcctrlv** [comment]
I'm having this issue today.

![image](https://github.com/mi-g/vdhcoapp/assets/838783/0af192bf-bafd-4703-b8b9-76cc8202c5cb)

**Comment by paulrouget** [comment]
> when running /usr/bin/vdhcoapp, is it on purpose that no any error message, log, diagnostic info or help message on stdout?

Yes, it is on purpose. The reason is that the coapp is "passive" and controlled by your browser. They communicate via stdin/stdout, so the coapp can't just print anything, as its stdout is used as a communication socket.

Now thinking about it … we could show some info via stderr. I filed an issue: #170.
