### ISSUE TITLE
Downloadhelper and Ubuntu 18.04

### ISSUE THREAD

**Issue by etanus11** [mi-g/vdhcoapp#80]
Hi,
When I wanted to download a video I am prompted to install the extra programme on Linux Ubuntu 18.04, and Firefox or Chromium browser. I downloaded and installed it but it is not detected. I tried with the .deb file and the tarball. but there is no difference.
What is the reason for this problem and how can it be rectified?
Thanks. Renate

**Comment by mi-g** [comment]
This app was mainly developed under Ubuntu 18.04 (then adapted to other platforms), so i can tell it is supposed to work in this environment.

A common issue when installing under linux is the following:
- you install the tarball as user
- you run the install command to setup the coapp manifests
- you change your mind, delete the files extracted from the tarball
- you install the deb package (hence as root)
- the coapp is not recognized by the browser

The reason is that the manifests created during the first install (the user one) are still there and pointing to files that do not exist any more, and those manifests take precedence over the second install (the root one).

The workaround consists of removing manually the manifest files. Those files are named `net.downloadhelper.coapp.json` in directories `~/.mozilla/native-messaging-hosts` and `~/.config/google-chrome/NativeMessagingHosts`.

Closing this bug, feel free to reopen if needed.
