### ISSUE TITLE
[Feature Request ]Add delay before download

### ISSUE THREAD

**Issue by JohnPlayerSpecial** [mi-g/vdhcoapp#86]
Hello dear Michel

I am a user of Video DownloadHelper browser add-on which I am using on Firefox on Ubuntu.

Fist of all, thanks for all your work and the app is very very  awesome!

By the way, I am asking you if it could be easily deployed a feature I find quite useful.
I have to download lots of video because I am attending engineering university which due to the current situation in the world right now has now become pretty much exclusively online.
Videos are hosted on Kaltura.

I have a slow internet connection, particularly on the day. 
During the night,  things get much better.

Here's my idea: I would like to be able to choose what to download, then queue them in a list without actually  downloading anything, so that I can continue to preserve bandwidth of my limited internet connection and surf the web on the day with a decent speed.
Then before going to bed I guess I could start the actual download by the means of a button.
Can such thing (the delay of video downloads ) be easily done?
(  if the download was time limited or with a time expire URL, I could just do it few minutes before the night )
Since I am on Linux, can the companion app be tweaked to accomplish my needs?
What could I do? 

Usually, when I need to bulk download things I use wget or youtube-dl, but as of with the University website I have two headaches.
1-  I have to find a way to authenticate to be able to download (they use SAML I seem to have guessed, but I am not a professional programmer, although I very much like as a hobby ) 
2-  When I use the feature within Video DownloadHelper to see the URL of the video and then copy paste it in the address bar,  a few KB m3u8 file gets downloaded, which is not what I need.

I thank you a lot and wish you happy holidays.

Have a nice day!
Bye,
Aldo

**Comment by mi-g** [comment]
Sorry but this is not the right place for such features. The VDH companion app is only a dumb toolbox used by the extension itself.  The place to discuss this would be the VDH forum (https://groups.google.com/g/video-downloadhelper-q-and-a). However this feature has been requested and discussed several times: the problem is that when you queue a download to be downloaded hours later, there are many chances the link will expire. Many sites implements that kind of expiration mechanism to prevent other sites to directly link the assets hosted at their place. I have no doubt this would work in some places but we wouldn't have the resource to offer support for the many cases where it won't work.

In case the video URL is permanent, if you use linux, you may try to use directly `ffmpeg -i <m3u8-url> my-video.mp4` and delay this command.
