### ISSUE TITLE
Expired Certificate

### ISSUE THREAD

**Issue by chump2010** [mi-g/vdhcoapp#92]
It appears that all the installers have expired certificates.  The latest one, 1.61, says:

Issued to: SARL ACLAP
Issued by: COMODO RSA Code Signing CA
Valid from 15/05/2018 to 15/05/2021.

**Comment by jeffersondarcy** [comment]
I can't install on mac - I suspect that's the reason why

**Comment by mi-g** [comment]
For Windows: the code signing certificate has been renewed on 15/05/2021 so it should be ok now (and no one else reported the issue so we are confident)

For Mac: the code is signed using our Apple developer's certificate. The problem with Mac is that in our case, it is not possible to sign the binaries inside the installer. But instead of clicking the downloaded .pkg file, open the Finder, go to the Downloads directory, right click on the .pkg file and pick "Open". After you accept the warning, the coapp should install successfully.

**Comment by chump2010** [comment]
Yes. It works fine on Windows now. Thank you.

**Comment by gretraholisi** [comment]
@mi-g 
> For Mac: The problem with Mac is that in our case, it is not possible to sign the binaries inside the installer. 

Why can't net.downloadhelper.coapp.app be signed?

**Comment by ashundi** [comment]
The Mac binary doesn't launch.  The dmg is signed but the latest versions (ex. Catalina 10.15.7 ) doesn't let launching a non-signed binary.  The pkg is not signed so I can't run it either.

**Comment by mi-g** [comment]
Instead of double clicking directly the downloaded `.pkg`, can you open the finder, go to the directory where the `.pkg` has been downloaded and open it from there ?

**Comment by ashundi** [comment]
I don't understand the difference. The pkg is a binary file, not a folder, not an executable.  Anyway, it doesn't work
<img width="386" alt="Screen Shot 2021-06-09 at 12 09 02 AM" src="https://user-images.githubusercontent.com/71647189/121291817-e9f9d700-c8b6-11eb-95fb-e231979c0078.png">
